//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVTracksScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class act_fleetpairing
    {
        public int fleet_pair_id { get; set; }
        public System.DateTime pair_start_date { get; set; }
        public Nullable<System.DateTime> pair_end_date { get; set; }
        public Nullable<System.DateTime> proposed_date { get; set; }
        public Nullable<int> fleet_parent_id { get; set; }
        public Nullable<int> fleet_child_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    }
}
