//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVTracksScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_fleet_mapping
    {
        public int id { get; set; }
        public string device_id { get; set; }
        public int fleet_id { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual md_fleet md_fleet { get; set; }
    }
}
