//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVTracksScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_data
    {
        public int id { get; set; }
        public string device_id { get; set; }
        public string device_type { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string position { get; set; }
        public Nullable<double> altitude { get; set; }
        public Nullable<double> speed_knots { get; set; }
        public Nullable<double> course { get; set; }
        public Nullable<int> satellites { get; set; }
        public Nullable<int> hdop { get; set; }
        public Nullable<int> battery { get; set; }
        public Nullable<int> cellular_strength { get; set; }
        public string device_status { get; set; }
        public string power_status { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    }
}
