//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVTracksScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_Geofence
    {
        public int geofenceID { get; set; }
        public string geofenceName { get; set; }
        public decimal lat1 { get; set; }
        public decimal long1 { get; set; }
        public decimal lat2 { get; set; }
        public decimal long2 { get; set; }
        public decimal lat3 { get; set; }
        public decimal long3 { get; set; }
        public decimal lat4 { get; set; }
        public decimal long4 { get; set; }
        public string coalAreaType { get; set; }
        public string fuelAreaType { get; set; }
        public byte cycleIdentifier { get; set; }
        public int orderGeofence { get; set; }
        public int tripSectionID { get; set; }
        public Nullable<int> portID { get; set; }
        public Nullable<int> layerZIndex { get; set; }
        public int distance { get; set; }
        public decimal upstreamSteamingDuration { get; set; }
        public decimal downstreamSteamingDuration { get; set; }
        public decimal upstreamSteamingDuration_MBP { get; set; }
        public decimal downstreamSteamingDuration_MBP { get; set; }
        public Nullable<decimal> avgDurationMinutes { get; set; }
        public byte status { get; set; }
        public Nullable<int> locationAreaID { get; set; }
    }
}
