//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVTracksScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class avtracksdbEntities : DbContext
    {
        public avtracksdbEntities()
            : base("name=avtracksdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<act_fleetpairing> act_fleetpairing { get; set; }
        public virtual DbSet<device_fleet_mapping> device_fleet_mapping { get; set; }
        public virtual DbSet<map_data> map_data { get; set; }
        public virtual DbSet<md_fleet> md_fleet { get; set; }
        public virtual DbSet<MD_Geofence> MD_Geofence { get; set; }
        public virtual DbSet<time_setup> time_setup { get; set; }
    }
}
